/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Classes.Relacion;
import Classes.Pelicula;
import Classes.Actor;
import Classes.AdvancedLinkedList;
import Classes.Historial;
import static Windows.Add_Relationship.cb_actor1;
import static Windows.Add_Movie.cb_año;
import edu.uci.ics.jung.algorithms.layout.CircleLayout;
import edu.uci.ics.jung.algorithms.layout.Layout;
import edu.uci.ics.jung.visualization.BasicVisualizationServer;
import edu.uci.ics.jung.visualization.decorators.ToStringLabeller;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.DefaultComboBoxModel;
import static Windows.Add_Actor.cb_peliculas;
import static Windows.Eliminar_Actor.cb_eliminarActor;
import static Windows.Eliminar_Relacion.cb_actor1Eliminar;
import edu.uci.ics.jung.graph.UndirectedSparseMultigraph;
import edu.uci.ics.jung.graph.util.EdgeType;
import javax.swing.JLabel;
import static Windows.Historial_Frame.label_historial;
import static Windows.Modificar_Actor.cb_modificarActor;
import static Windows.Modificar_Actor.cb_peliculasModificar;

/**
 *
 * @author Memo
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();

        Actor Kevin_Bacon = new Actor("Kevin Norwood Bacon", 57, "Estadounidense");
        actores.insert(Kevin_Bacon);
        Pelicula p1 = new Pelicula("National Lampoon's Animal House", 1978, "Universal Pictures");
        Pelicula p2 = new Pelicula("Friday the 13th", 1980, "Sean S. Cunningham Films");
        peliculas.insert(p1);
        peliculas.insert(p2);
        Kevin_Bacon.setPeliculas(p1);
        Kevin_Bacon.setPeliculas(p2);
        grafo.addVertex(Kevin_Bacon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AddJMenu = new javax.swing.JMenu();
        JMenuAddActor = new javax.swing.JMenuItem();
        JMenuAddMovie = new javax.swing.JMenuItem();
        JMenuAddRelacion = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        EditActor = new javax.swing.JMenuItem();
        EditRelacion = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenu();
        DeleteActor = new javax.swing.JMenuItem();
        DeleteRelacion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        JMenuItemHistory = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItem6.setText("Pseudo Bacon Number Calculator");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        AddJMenu.setText("Add");

        JMenuAddActor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JMenuAddActor.setText("Actor");
        JMenuAddActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuAddActorActionPerformed(evt);
            }
        });
        AddJMenu.add(JMenuAddActor);

        JMenuAddMovie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        JMenuAddMovie.setText("Movie");
        JMenuAddMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuAddMovieActionPerformed(evt);
            }
        });
        AddJMenu.add(JMenuAddMovie);

        JMenuAddRelacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        JMenuAddRelacion.setText("Relacion");
        JMenuAddRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuAddRelacionActionPerformed(evt);
            }
        });
        AddJMenu.add(JMenuAddRelacion);

        jMenu2.add(AddJMenu);

        Edit.setText("Edit");

        EditActor.setText("Actor");
        EditActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActorActionPerformed(evt);
            }
        });
        Edit.add(EditActor);

        EditRelacion.setText("Relacion");
        EditRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditRelacionActionPerformed(evt);
            }
        });
        Edit.add(EditRelacion);

        jMenu2.add(Edit);

        Delete.setText("Delete");

        DeleteActor.setText("Actor");
        DeleteActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActorActionPerformed(evt);
            }
        });
        Delete.add(DeleteActor);

        DeleteRelacion.setText("Relacion");
        DeleteRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRelacionActionPerformed(evt);
            }
        });
        Delete.add(DeleteRelacion);

        jMenu2.add(Delete);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("View");

        jMenuItem1.setText("HollyWood Universe");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        JMenuItemHistory.setText("History");
        JMenuItemHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemHistoryActionPerformed(evt);
            }
        });
        jMenu4.add(JMenuItemHistory);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < relaciones.size(); i++) {
            grafo.addEdge(relaciones.get(i), relaciones.get(i).getActor(), relaciones.get(i).getActor2(), EdgeType.UNDIRECTED);
        }
        
        Layout<Integer, String> layout = new CircleLayout(grafo);
        layout.setSize(new Dimension(550, 550));
        BasicVisualizationServer<Integer, String> visualization = new BasicVisualizationServer<Integer, String>(layout);
        visualization.setPreferredSize(new Dimension(600, 600));
        visualization.getRenderContext().setLabelOffset(20);
        visualization.getRenderContext().setVertexLabelTransformer(new ToStringLabeller());
        visualization.getRenderContext().setEdgeLabelTransformer(new ToStringLabeller());
        JFrame frame = new JFrame("Hollywood");
        frame.getContentPane().add(visualization);

        frame.pack();
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JMenuAddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuAddMovieActionPerformed
        // TODO add your handling code here:

        Add_Movie movies = new Add_Movie();

        movies.pack();
        movies.setVisible(true);
        movies.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("----");
        for (int i = 1888; i <= 2015; i++) {
            model.addElement(i);
        }
        cb_año.setModel(model);

    }//GEN-LAST:event_JMenuAddMovieActionPerformed

    private void JMenuAddActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuAddActorActionPerformed
        // TODO add your handling code here:
        Add_Actor actors = new Add_Actor();
        actors.pack();
        actors.setVisible(true);
        actors.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("----Seleccione una Pelicula ------");
        for (int i = 0; i < peliculas.size(); i++) {
            model.addElement(peliculas.get(i));
        }
        cb_peliculas.setModel(model);
    }//GEN-LAST:event_JMenuAddActorActionPerformed

    private void JMenuAddRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuAddRelacionActionPerformed
        // TODO add your handling code here:
        Add_Relationship relacion = new Add_Relationship();
        relacion.pack();
        relacion.setVisible(true);
        relacion.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < actores.size(); i++) {
            System.out.println(actores.get(i));
            model.addElement(actores.get(i));
        }
        cb_actor1.setModel(model);

    }//GEN-LAST:event_JMenuAddRelacionActionPerformed

    private void JMenuItemHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemHistoryActionPerformed
        // TODO add your handling code here:
        Historial_Frame historialframe = new Historial_Frame();
        historialframe.pack();
        historialframe.setVisible(true);
        historialframe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        JLabel label = new JLabel();
        label.setText(historial.seeHistorial());
        label_historial.setText(label.getText());
        
    }//GEN-LAST:event_JMenuItemHistoryActionPerformed

    private void EditActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActorActionPerformed
        // TODO add your handling code here:
        Modificar_Actor modificar_actor = new Modificar_Actor();
        modificar_actor.pack();
        modificar_actor.setVisible(true);
        modificar_actor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < actores.size(); i++) {
            System.out.println(actores.get(i));
            model.addElement(actores.get(i));
        }
        DefaultComboBoxModel modelmovie = new DefaultComboBoxModel();
        modelmovie.addElement("----Seleccione una Pelicula ------");
        for (int i = 0; i < peliculas.size(); i++) {
            modelmovie.addElement(peliculas.get(i));
        }
        cb_peliculasModificar.setModel(modelmovie);
        cb_modificarActor.setModel(model);
        
    }//GEN-LAST:event_EditActorActionPerformed

    private void DeleteActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActorActionPerformed
        // TODO add your handling code here:
        Eliminar_Actor eliminar_actor = new Eliminar_Actor();
        eliminar_actor.pack();
        eliminar_actor.setVisible(true);
        eliminar_actor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < actores.size(); i++) {
            System.out.println(actores.get(i));
            model.addElement(actores.get(i));
        }
        
        cb_eliminarActor.setModel(model);
        
    }//GEN-LAST:event_DeleteActorActionPerformed

    private void EditRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditRelacionActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_EditRelacionActionPerformed

    private void DeleteRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRelacionActionPerformed
        // TODO add your handling code here:
         Eliminar_Relacion relacion_e = new Eliminar_Relacion();
        relacion_e.pack();
        relacion_e.setVisible(true);
        relacion_e.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < actores.size(); i++) {
            System.out.println(actores.get(i));
            model.addElement(actores.get(i));
        }
        cb_actor1Eliminar.setModel(model);
    }//GEN-LAST:event_DeleteRelacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AddJMenu;
    private javax.swing.JMenu Delete;
    private javax.swing.JMenuItem DeleteActor;
    private javax.swing.JMenuItem DeleteRelacion;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem EditActor;
    private javax.swing.JMenuItem EditRelacion;
    private javax.swing.JMenuItem JMenuAddActor;
    private javax.swing.JMenuItem JMenuAddMovie;
    private javax.swing.JMenuItem JMenuAddRelacion;
    private javax.swing.JMenuItem JMenuItemHistory;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
UndirectedSparseMultigraph grafo = new UndirectedSparseMultigraph<Actor, Relacion>();
   //public static ArrayList<Actor> actores = new ArrayList();
   //public static ArrayList<Pelicula> peliculas = new ArrayList();
   public static ArrayList<Relacion> relaciones = new ArrayList();
    public static AdvancedLinkedList actores = new AdvancedLinkedList();
    public static AdvancedLinkedList peliculas = new AdvancedLinkedList();
    public static Historial historial = new Historial();
    //public static AdvancedLinkedList relaciones = new AdvancedLinkedList();
}
