/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Classes.Actor;
import Classes.Historial;
import Classes.Relacion;
import static Windows.MainWindow.relaciones;
import java.util.ArrayList;
import static javafx.scene.input.KeyCode.R;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class Modificar_Relacion extends javax.swing.JFrame {

    /**
     * Creates new form Modificar_Relacion
     */
    public Modificar_Relacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_actor1Modificar = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cb_relacionModificar = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cb_actor2Modificar = new javax.swing.JComboBox();
        ModificarRelacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Actor 1: ");

        cb_actor1Modificar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_actor1ModificarItemStateChanged(evt);
            }
        });

        jLabel3.setText("Relacion: ");

        cb_relacionModificar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------", "Amistad", "Familia", "Noviazgo", "Matrimonio" }));

        jLabel2.setText("Actor 2: ");

        ModificarRelacion.setText("Modificar");
        ModificarRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarRelacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_actor1Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_actor2Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cb_relacionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ModificarRelacion)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_actor1Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_actor2Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cb_relacionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModificarRelacion))))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_actor1ModificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_actor1ModificarItemStateChanged
        // TODO add your handling code here:
        actors = new ArrayList();
        for (int i = 0; i < cb_actor1Modificar.getItemCount(); i++) {
            actors.add((Actor) cb_actor1Modificar.getItemAt(i));
        }
        for (int i = 0; i < actors.size(); i++) {
            if (cb_actor1Modificar.getItemAt(cb_actor1Modificar.getSelectedIndex()) == actors.get(i)) {
                actors.remove(i);
            }
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < actors.size(); i++) {
            model.addElement(actors.get(i));
        }
        cb_actor2Modificar.setModel(model);
    }//GEN-LAST:event_cb_actor1ModificarItemStateChanged

    private void ModificarRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarRelacionActionPerformed
        // TODO add your handling code here:
        Historial historial = new Historial();
        if (cb_relacionModificar.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Relacion indefinida, porfavor escoja una relacion......");
        }else{
            R = new Relacion(cb_relacionModificar.getSelectedIndex(), (Actor)cb_actor1Modificar.getSelectedItem(),(Actor) cb_actor2Modificar.getSelectedItem());
            //relaciones.get(cb_relacionModificar.getSelectedIndex());
            relaciones.set(cb_relacionModificar.getSelectedIndex(), R );
            historial.setHistorial("Se modifico la relacion "+cb_relacionModificar.getSelectedItem().toString()+" entre "+cb_actor1Modificar.getSelectedItem().toString()+" y "+cb_actor2Modificar.getSelectedItem().toString());
        }
    }//GEN-LAST:event_ModificarRelacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Relacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Relacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Relacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Relacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_Relacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModificarRelacion;
    public static javax.swing.JComboBox cb_actor1Modificar;
    public static javax.swing.JComboBox cb_actor2Modificar;
    private javax.swing.JComboBox cb_relacionModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    ArrayList<Actor> actors;
    Relacion R;
}
